name: audio-switcher # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Simple script to switch between audio output sinks # 79 char long summary
description: |
  An ultra-simple bash script that switches between pulseaudio output sinks and moves all the audio sources over.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  audio-switcher:
    # See 'snapcraft plugins'
    plugin: dump
    source: https://github.com/tylnesh/audio-switcher.git
    stage-packages: 
       - pulseaudio
       - libnotify-bin
       
apps:
  audio-switcher:
    command: audio-switcher.sh
    plugs:
      - network
      - desktop      
